---
title: Dart语言入门：13、异常处理
tags:
  - Dart
  - Dart语言入门
categories:
  - Dart
  - Basics
date: 2018-11-29 22:56:21
---

# 一、Throw
抛出一个异常：
```
throw FormatException('Expected at least 1 section');
```

也可以抛出其他对象：
```
throw 'Out of autoref.cn!';
```

因为抛出异常是一个表达式，所以可以用在 => 语句中：
```
void distanceTo(Point other) => throw UnimplementedError();
```

# 二、Catch
捕获一个异常：
```
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  buyMoreLlamas();
}
```

捕获多个异常：
```
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  // 一个特定的异常
  buyMoreLlamas();
} on Exception catch (e) {
  // 其他异常
  print('Unknown exception: $e');
} catch (e) {
  // 没有指定类型, 则处理所有
  print('Something really unknown: $e');
}
```

catch()可以指定一个或两个参数，第一个参数是exception，第二个是stack trace（一个StackTrace对象）：
```
try {
  // ···
} on Exception catch (e) {
  print('Exception details:\n $e');
} catch (e, s) {
  print('Exception details:\n $e');
  print('Stack trace:\n $s');
}
```

使用rethrow关键字，继续向上抛出异常：
```
void misbehave() {
  try {
    dynamic foo = true;
    print(foo++); // Runtime error
  } catch (e) {
    print('misbehave() partially handled ${e.runtimeType}.');
    rethrow; // 允许调用者看到这个异常
  }
}

void main() {
  try {
    misbehave();
  } catch (e) {
    print('main() finished handling ${e.runtimeType}.');
  }
}
```

# 三、Finally
不管有无异常，都会执行finally分句：
```
try {
  breedMoreLlamas();
} finally {
  // 即使有异常，也会执行
  cleanLlamaStalls();
}
```

在所有匹配catch分句后执行：
```
try {
  breedMoreLlamas();
} catch (e) {
  print('Error: $e'); // 先处理异常
} finally {
  cleanLlamaStalls(); // 然后清理
}
```